name: Put docs in another branch

on:
  push:
    branches: [main]

jobs:
  create-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: create a file
        run: mkdir mkdocs && cd mkdocs && echo "${{ github.run_id }} -- ${{ github.run_number }}" >> a_file.txt

      - name: Push
        - uses: casperdcl/push-dir@v1
        with:
          message: update static site
          branch: docs
          dir: mkdocs