name: Put docs in another branch

on:
  push:
    branches: [main]

jobs:
  create-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir mkdocs && cd mkdocs && echo "${{ github.run_id }} -- ${{ github.run_number }}" >> a_file.txt
      - run: cp some_docs.txt ./mkdocs/

      - name: Create docs
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: docs
          email: akashpalrecha@gmail.com
          build_dir: mkdocs
          commit_message: creating docs please make this work!
